version: '3.7'

services:
    mysql:
        container_name: ecommerce-mysql
        image: docker.io/bitnami/mysql:latest
        ports:
            - '3306:3306'
        volumes:
            - 'mysql_data:/bitnami/mysql/data'
        environment:    
            # - MYSQL_USER= < UserName > | Default user 'root'  
              - MYSQL_DATABASE=ECommerce
              - MYSQL_ROOT_PASSWORD=12345
              - ALLOW_EMPTY_PASSWORD=no
        healthcheck:
          test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
          interval: 15s
          timeout: 5s
          retries: 6

volumes:
  mysql_data:
    driver: local
